export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const GET_GENRES = "GET_GENRES";
export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
export const FILTER_BY_API_OR_DB = "FILTER_BY_API_OR_DB";
export const ALPHABETICAL_SORT = "ALPHABETICAL_SORT";
export const SORT_BY_RATING = "SORT_BY_RATING";
